#!/bin/bash
cd /home/pi/pits/tracker

# Turn Pi LED0 on in heartbeat mode to signify PITS startup
echo 255 | sudo tee /sys/class/leds/led0/brightness
echo heartbeat | sudo tee /sys/class/leds/led0/trigger
# After 30 seconds turn off LED0 to save power
(sleep 30; echo 0 | sudo tee /sys/class/leds/led0/brightness) &

sudo ./camera 2>&1 | sudo tee /home/pi/pits/tracker/camera.txt &

# sleep 30
# sudo python3 gopro.py &
# python3 sensors.py &
# python3 astro_led.py &
# python3 webstuff.py
# sudo python3 gopro.py &
while :
do
	sudo ./tracker
	sleep 5
done

