#!/bin/bash
cd /home/pi/pits/tracker
#./send_aprs &
echo heartbeat | sudo tee /sys/class/leds/led0/trigger
(sleep 30; echo 0 | sudo tee /sys/class/leds/led0/brightness) &
sudo ./camera 2>&1 | sudo tee /home/pi/pits/tracker/camera.txt > /dev/null &
# sleep 30
# sudo python3 gopro.py &
# python3 sensors.py &
# python3 astro_led.py &
# python3 webstuff.py
while :
do
	sudo ./tracker
	sleep 5
done

